anger:
  keyframes:
  - joints:
      motor_front: 860
      motor_back_left: 859
      motor_back_right: 860
      lazy_susan: 579
    duration: 0.0
  - joints:
      motor_front: 862
      motor_back_left: 858
      motor_back_right: 859
      lazy_susan: 580
    duration: 0.101
  - joints:
      motor_front: 862
      motor_back_left: 858
      motor_back_right: 859
      lazy_susan: 582
    duration: 0.102
  - joints:
      motor_front: 863
      motor_back_left: 858
      motor_back_right: 857
      lazy_susan: 586
    duration: 0.101
  - joints:
      motor_front: 863
      motor_back_left: 858
      motor_back_right: 858
      lazy_susan: 588
    duration: 0.1
  - joints:
      motor_front: 860
      motor_back_left: 859
      motor_back_right: 860
      lazy_susan: 590
    duration: 0.1
  - joints:
      motor_front: 853
      motor_back_left: 858
      motor_back_right: 868
      lazy_susan: 576
    duration: 0.101
  - joints:
      motor_front: 803
      motor_back_left: 875
      motor_back_right: 901
      lazy_susan: 468
    duration: 0.101
  - joints:
      motor_front: 723
      motor_back_left: 964
      motor_back_right: 892
      lazy_susan: 321
    duration: 0.102
  - joints:
      motor_front: 693
      motor_back_left: 1011
      motor_back_right: 881
      lazy_susan: 323
    duration: 0.104
  - joints:
      motor_front: 736
      motor_back_left: 944
      motor_back_right: 899
      lazy_susan: 447
    duration: 0.1
  - joints:
      motor_front: 764
      motor_back_left: 954
      motor_back_right: 865
      lazy_susan: 350
    duration: 0.1
  - joints:
      motor_front: 770
      motor_back_left: 955
      motor_back_right: 852
      lazy_susan: 338
    duration: 0.101
  - joints:
      motor_front: 763
      motor_back_left: 935
      motor_back_right: 881
      lazy_susan: 438
    duration: 0.106
  - joints:
      motor_front: 760
      motor_back_left: 950
      motor_back_right: 871
      lazy_susan: 303
    duration: 0.104
  - joints:
      motor_front: 753
      motor_back_left: 945
      motor_back_right: 882
      lazy_susan: 356
    duration: 0.101
  - joints:
      motor_front: 773
      motor_back_left: 917
      motor_back_right: 889
      lazy_susan: 431
    duration: 0.102
  - joints:
      motor_front: 834
      motor_back_left: 855
      motor_back_right: 890
      lazy_susan: 628
    duration: 0.104
  - joints:
      motor_front: 831
      motor_back_left: 822
      motor_back_right: 926
      lazy_susan: 819
    duration: 0.102
  - joints:
      motor_front: 809
      motor_back_left: 817
      motor_back_right: 952
      lazy_susan: 928
    duration: 0.102
  - joints:
      motor_front: 781
      motor_back_left: 835
      motor_back_right: 962
      lazy_susan: 884
    duration: 0.101
  - joints:
      motor_front: 743
      motor_back_left: 885
      motor_back_right: 951
      lazy_susan: 835
    duration: 0.1
  - joints:
      motor_front: 788
      motor_back_left: 834
      motor_back_right: 957
      lazy_susan: 948
    duration: 0.101
  - joints:
      motor_front: 738
      motor_back_left: 869
      motor_back_right: 979
      lazy_susan: 936
    duration: 0.101
  - joints:
      motor_front: 747
      motor_back_left: 874
      motor_back_right: 960
      lazy_susan: 917
    duration: 0.102
  - joints:
      motor_front: 766
      motor_back_left: 844
      motor_back_right: 968
      lazy_susan: 972
    duration: 0.104
  - joints:
      motor_front: 744
      motor_back_left: 876
      motor_back_right: 961
      lazy_susan: 911
    duration: 0.105
  - joints:
      motor_front: 766
      motor_back_left: 840
      motor_back_right: 972
      lazy_susan: 977
    duration: 0.105
  - joints:
      motor_front: 739
      motor_back_left: 851
      motor_back_right: 980
      lazy_susan: 946
    duration: 0.102
  - joints:
      motor_front: 739
      motor_back_left: 851
      motor_back_right: 980
      lazy_susan: 946
    duration: 0.103
  - joints:
      motor_front: 712
      motor_back_left: 984
      motor_back_right: 885
      lazy_susan: 672
    duration: 0.102
  - joints:
      motor_front: 746
      motor_back_left: 963
      motor_back_right: 872
      lazy_susan: 604
    duration: 0.104
  - joints:
      motor_front: 779
      motor_back_left: 942
      motor_back_right: 856
      lazy_susan: 571
    duration: 0.101
  - joints:
      motor_front: 803
      motor_back_left: 921
      motor_back_right: 855
      lazy_susan: 559
    duration: 0.103
  - joints:
      motor_front: 821
      motor_back_left: 902
      motor_back_right: 856
      lazy_susan: 559
    duration: 0.101
  - joints:
      motor_front: 841
      motor_back_left: 885
      motor_back_right: 853
      lazy_susan: 561
    duration: 0.103
  - joints:
      motor_front: 860
      motor_back_left: 868
      motor_back_right: 850
      lazy_susan: 565
    duration: 0.103
  - joints:
      motor_front: 868
      motor_back_left: 859
      motor_back_right: 852
      lazy_susan: 565
    duration: 0.105
  - joints:
      motor_front: 868
      motor_back_left: 855
      motor_back_right: 856
      lazy_susan: 564
    duration: 0.104
  - joints:
      motor_front: 868
      motor_back_left: 848
      motor_back_right: 863
      lazy_susan: 564
    duration: 0.104
  - joints:
      motor_front: 869
      motor_back_left: 847
      motor_back_right: 863
      lazy_susan: 566
    duration: 0.104
  - joints:
      motor_front: 868
      motor_back_left: 849
      motor_back_right: 862
      lazy_susan: 569
    duration: 0.105
  - joints:
      motor_front: 869
      motor_back_left: 849
      motor_back_right: 861
      lazy_susan: 568
    duration: 0.105
  - joints:
      motor_front: 870
      motor_back_left: 848
      motor_back_right: 861
      lazy_susan: 568
    duration: 0.104
  - joints:
      motor_front: 869
      motor_back_left: 848
      motor_back_right: 862
      lazy_susan: 569
    duration: 0.105
  - joints:
      motor_front: 871
      motor_back_left: 849
      motor_back_right: 859
      lazy_susan: 570
    duration: 0.104
  - joints:
      motor_front: 871
      motor_back_left: 848
      motor_back_right: 860
      lazy_susan: 571
    duration: 0.104
  - joints:
      motor_front: 872
      motor_back_left: 848
      motor_back_right: 859
      lazy_susan: 573
    duration: 0.102
  - joints:
      motor_front: 874
      motor_back_left: 848
      motor_back_right: 858
      lazy_susan: 573
    duration: 0.101
  - joints:
      motor_front: 873
      motor_back_left: 846
      motor_back_right: 859
      lazy_susan: 569
    duration: 0.105
  - joints:
      motor_front: 874
      motor_back_left: 846
      motor_back_right: 859
      lazy_susan: 568
    duration: 0.105
  - joints:
      motor_front: 877
      motor_back_left: 844
      motor_back_right: 858
      lazy_susan: 568
    duration: 0.104
