bounce_smooth:
  keyframes:
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.0
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1010
      motor_back_left: 1010
      motor_back_right: 1010
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1010
      motor_back_left: 1010
      motor_back_right: 1010
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 928
      motor_back_left: 928
      motor_back_right: 928
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 879
      motor_back_left: 879
      motor_back_right: 879
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 830
      motor_back_left: 830
      motor_back_right: 830
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 830
      motor_back_left: 830
      motor_back_right: 830
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 879
      motor_back_left: 879
      motor_back_right: 879
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 928
      motor_back_left: 928
      motor_back_right: 928
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1000
      motor_back_left: 1000
      motor_back_right: 1000
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1023
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 1000
      motor_back_left: 1000
      motor_back_right: 1000
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 928
      motor_back_left: 928
      motor_back_right: 928
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 879
      motor_back_left: 879
      motor_back_right: 879
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 830
      motor_back_left: 830
      motor_back_right: 830
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 815
      motor_back_left: 815
      motor_back_right: 815
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 850
      motor_back_left: 850
      motor_back_right: 850
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 885
      motor_back_left: 885
      motor_back_right: 885
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 918
      motor_back_left: 918
      motor_back_right: 918
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 934
      motor_back_left: 934
      motor_back_right: 934
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 948
      motor_back_left: 948
      motor_back_right: 948
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 961
      motor_back_left: 961
      motor_back_right: 961
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 961
      motor_back_left: 961
      motor_back_right: 961
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 948
      motor_back_left: 948
      motor_back_right: 948
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 934
      motor_back_left: 934
      motor_back_right: 934
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 918
      motor_back_left: 918
      motor_back_right: 918
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 885
      motor_back_left: 885
      motor_back_right: 885
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 850
      motor_back_left: 850
      motor_back_right: 850
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 815
      motor_back_left: 815
      motor_back_right: 815
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 801
      motor_back_left: 801
      motor_back_right: 801
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 821
      motor_back_left: 821
      motor_back_right: 821
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 840
      motor_back_left: 840
      motor_back_right: 840
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 860
      motor_back_left: 860
      motor_back_right: 860
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 869
      motor_back_left: 869
      motor_back_right: 869
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 879
      motor_back_left: 879
      motor_back_right: 879
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 889
      motor_back_left: 889
      motor_back_right: 889
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 899
      motor_back_left: 899
      motor_back_right: 899
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 889
      motor_back_left: 889
      motor_back_right: 889
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 879
      motor_back_left: 879
      motor_back_right: 879
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 869
      motor_back_left: 869
      motor_back_right: 869
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 860
      motor_back_left: 860
      motor_back_right: 860
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 840
      motor_back_left: 840
      motor_back_right: 840
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 821
      motor_back_left: 821
      motor_back_right: 821
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 801
      motor_back_left: 801
      motor_back_right: 801
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 797
      motor_back_left: 797
      motor_back_right: 797
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 811
      motor_back_left: 811
      motor_back_right: 811
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 824
      motor_back_left: 824
      motor_back_right: 824
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 840
      motor_back_left: 840
      motor_back_right: 840
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 846
      motor_back_left: 846
      motor_back_right: 846
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 850
      motor_back_left: 850
      motor_back_right: 850
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 856
      motor_back_left: 856
      motor_back_right: 856
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 860
      motor_back_left: 860
      motor_back_right: 860
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 856
      motor_back_left: 856
      motor_back_right: 856
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 850
      motor_back_left: 850
      motor_back_right: 850
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 846
      motor_back_left: 846
      motor_back_right: 846
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 840
      motor_back_left: 840
      motor_back_right: 840
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 824
      motor_back_left: 824
      motor_back_right: 824
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 811
      motor_back_left: 811
      motor_back_right: 811
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 797
      motor_back_left: 797
      motor_back_right: 797
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 791
      motor_back_left: 791
      motor_back_right: 791
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 801
      motor_back_left: 801
      motor_back_right: 801
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 811
      motor_back_left: 811
      motor_back_right: 811
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 821
      motor_back_left: 821
      motor_back_right: 821
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 811
      motor_back_left: 811
      motor_back_right: 811
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 801
      motor_back_left: 801
      motor_back_right: 801
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 791
      motor_back_left: 791
      motor_back_right: 791
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 782
      motor_back_left: 782
      motor_back_right: 782
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 830
      motor_back_left: 830
      motor_back_right: 830
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 879
      motor_back_left: 879
      motor_back_right: 879
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 928
      motor_back_left: 928
      motor_back_right: 928
      lazy_susan: 586
    duration: 0.075
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.075
