dance1_1:
  keyframes:
  - joints:
      motor_front: 957
      motor_back_left: 977
      motor_back_right: 918
      lazy_susan: 586
    duration: 0.0
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.265
  - joints:
      motor_front: 957
      motor_back_left: 977
      motor_back_right: 918
      lazy_susan: 586
    duration: 0.266
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.265
  - joints:
      motor_front: 957
      motor_back_left: 918
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.266
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.265
  - joints:
      motor_front: 957
      motor_back_left: 918
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.266
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.265
  - joints:
      motor_front: 957
      motor_back_left: 977
      motor_back_right: 918
      lazy_susan: 586
    duration: 0.266
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.265
  - joints:
      motor_front: 957
      motor_back_left: 977
      motor_back_right: 918
      lazy_susan: 586
    duration: 0.266
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.265
  - joints:
      motor_front: 957
      motor_back_left: 918
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.266
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.265
  - joints:
      motor_front: 957
      motor_back_left: 918
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.266
  - joints:
      motor_front: 977
      motor_back_left: 977
      motor_back_right: 977
      lazy_susan: 586
    duration: 0.265
