fear:
  keyframes:
  - joints:
      motor_front: 894
      motor_back_left: 825
      motor_back_right: 860
      lazy_susan: 575
    duration: 0.0
  - joints:
      motor_front: 894
      motor_back_left: 828
      motor_back_right: 857
      lazy_susan: 575
    duration: 0.104
  - joints:
      motor_front: 889
      motor_back_left: 830
      motor_back_right: 860
      lazy_susan: 576
    duration: 0.101
  - joints:
      motor_front: 883
      motor_back_left: 831
      motor_back_right: 865
      lazy_susan: 576
    duration: 0.102
  - joints:
      motor_front: 883
      motor_back_left: 831
      motor_back_right: 866
      lazy_susan: 576
    duration: 0.102
  - joints:
      motor_front: 883
      motor_back_left: 831
      motor_back_right: 866
      lazy_susan: 576
    duration: 0.105
  - joints:
      motor_front: 879
      motor_back_left: 834
      motor_back_right: 866
      lazy_susan: 578
    duration: 0.101
  - joints:
      motor_front: 873
      motor_back_left: 837
      motor_back_right: 869
      lazy_susan: 578
    duration: 0.103
  - joints:
      motor_front: 859
      motor_back_left: 852
      motor_back_right: 868
      lazy_susan: 578
    duration: 0.1
  - joints:
      motor_front: 895
      motor_back_left: 837
      motor_back_right: 847
      lazy_susan: 581
    duration: 0.105
  - joints:
      motor_front: 1023
      motor_back_left: 725
      motor_back_right: 757
      lazy_susan: 580
    duration: 0.102
  - joints:
      motor_front: 1023
      motor_back_left: 725
      motor_back_right: 757
      lazy_susan: 580
    duration: 0.103
  - joints:
      motor_front: 1023
      motor_back_left: 621
      motor_back_right: 701
      lazy_susan: 550
    duration: 0.104
  - joints:
      motor_front: 1023
      motor_back_left: 631
      motor_back_right: 703
      lazy_susan: 556
    duration: 0.103
  - joints:
      motor_front: 1023
      motor_back_left: 631
      motor_back_right: 707
      lazy_susan: 555
    duration: 0.105
  - joints:
      motor_front: 1023
      motor_back_left: 618
      motor_back_right: 721
      lazy_susan: 536
    duration: 0.104
  - joints:
      motor_front: 1023
      motor_back_left: 616
      motor_back_right: 724
      lazy_susan: 533
    duration: 0.104
  - joints:
      motor_front: 1023
      motor_back_left: 563
      motor_back_right: 770
      lazy_susan: 455
    duration: 0.103
  - joints:
      motor_front: 1023
      motor_back_left: 530
      motor_back_right: 952
      lazy_susan: 312
    duration: 0.104
  - joints:
      motor_front: 1023
      motor_back_left: 512
      motor_back_right: 989
      lazy_susan: 233
    duration: 0.104
  - joints:
      motor_front: 1023
      motor_back_left: 509
      motor_back_right: 984
      lazy_susan: 254
    duration: 0.102
  - joints:
      motor_front: 1023
      motor_back_left: 532
      motor_back_right: 947
      lazy_susan: 402
    duration: 0.101
  - joints:
      motor_front: 1023
      motor_back_left: 532
      motor_back_right: 947
      lazy_susan: 402
    duration: 0.102
  - joints:
      motor_front: 1023
      motor_back_left: 648
      motor_back_right: 700
      lazy_susan: 641
    duration: 0.105
  - joints:
      motor_front: 1023
      motor_back_left: 721
      motor_back_right: 662
      lazy_susan: 806
    duration: 0.106
  - joints:
      motor_front: 1023
      motor_back_left: 716
      motor_back_right: 670
      lazy_susan: 784
    duration: 0.1
  - joints:
      motor_front: 1023
      motor_back_left: 663
      motor_back_right: 754
      lazy_susan: 625
    duration: 0.1
  - joints:
      motor_front: 1023
      motor_back_left: 673
      motor_back_right: 771
      lazy_susan: 545
    duration: 0.101
  - joints:
      motor_front: 1023
      motor_back_left: 679
      motor_back_right: 774
      lazy_susan: 499
    duration: 0.101
  - joints:
      motor_front: 1023
      motor_back_left: 671
      motor_back_right: 762
      lazy_susan: 476
    duration: 0.102
  - joints:
      motor_front: 1023
      motor_back_left: 647
      motor_back_right: 743
      lazy_susan: 494
    duration: 0.103
  - joints:
      motor_front: 1023
      motor_back_left: 646
      motor_back_right: 703
      lazy_susan: 542
    duration: 0.101
  - joints:
      motor_front: 1023
      motor_back_left: 661
      motor_back_right: 704
      lazy_susan: 574
    duration: 0.1
  - joints:
      motor_front: 1023
      motor_back_left: 674
      motor_back_right: 725
      lazy_susan: 583
    duration: 0.101
  - joints:
      motor_front: 1023
      motor_back_left: 687
      motor_back_right: 745
      lazy_susan: 584
    duration: 0.103
  - joints:
      motor_front: 1023
      motor_back_left: 702
      motor_back_right: 770
      lazy_susan: 588
    duration: 0.104
  - joints:
      motor_front: 1023
      motor_back_left: 726
      motor_back_right: 798
      lazy_susan: 591
    duration: 0.103
  - joints:
      motor_front: 1010
      motor_back_left: 749
      motor_back_right: 819
      lazy_susan: 594
    duration: 0.101
  - joints:
      motor_front: 973
      motor_back_left: 768
      motor_back_right: 838
      lazy_susan: 596
    duration: 0.101
  - joints:
      motor_front: 941
      motor_back_left: 781
      motor_back_right: 855
      lazy_susan: 596
    duration: 0.101
  - joints:
      motor_front: 907
      motor_back_left: 781
      motor_back_right: 891
      lazy_susan: 591
    duration: 0.105
  - joints:
      motor_front: 902
      motor_back_left: 788
      motor_back_right: 889
      lazy_susan: 592
    duration: 0.105
  - joints:
      motor_front: 892
      motor_back_left: 802
      motor_back_right: 885
      lazy_susan: 595
    duration: 0.101
  - joints:
      motor_front: 892
      motor_back_left: 802
      motor_back_right: 885
      lazy_susan: 595
    duration: 0.1
  - joints:
      motor_front: 878
      motor_back_left: 820
      motor_back_right: 881
      lazy_susan: 596
    duration: 0.101
  - joints:
      motor_front: 878
      motor_back_left: 824
      motor_back_right: 877
      lazy_susan: 596
    duration: 0.1
  - joints:
      motor_front: 881
      motor_back_left: 825
      motor_back_right: 872
      lazy_susan: 595
    duration: 0.104
  - joints:
      motor_front: 882
      motor_back_left: 828
      motor_back_right: 870
      lazy_susan: 593
    duration: 0.103
  - joints:
      motor_front: 885
      motor_back_left: 829
      motor_back_right: 865
      lazy_susan: 592
    duration: 0.103
  - joints:
      motor_front: 886
      motor_back_left: 829
      motor_back_right: 864
      lazy_susan: 593
    duration: 0.103
  - joints:
      motor_front: 886
      motor_back_left: 832
      motor_back_right: 861
      lazy_susan: 593
    duration: 0.103
  - joints:
      motor_front: 889
      motor_back_left: 833
      motor_back_right: 857
      lazy_susan: 593
    duration: 0.101
