happy:
  keyframes:
  - joints:
      motor_front: 851
      motor_back_left: 852
      motor_back_right: 844
      lazy_susan: 567
    duration: 0.0
  - joints:
      motor_front: 850
      motor_back_left: 853
      motor_back_right: 843
      lazy_susan: 567
    duration: 0.103
  - joints:
      motor_front: 850
      motor_back_left: 852
      motor_back_right: 844
      lazy_susan: 566
    duration: 0.102
  - joints:
      motor_front: 851
      motor_back_left: 853
      motor_back_right: 843
      lazy_susan: 566
    duration: 0.101
  - joints:
      motor_front: 850
      motor_back_left: 854
      motor_back_right: 843
      lazy_susan: 566
    duration: 0.103
  - joints:
      motor_front: 851
      motor_back_left: 853
      motor_back_right: 842
      lazy_susan: 566
    duration: 0.104
  - joints:
      motor_front: 851
      motor_back_left: 853
      motor_back_right: 843
      lazy_susan: 567
    duration: 0.104
  - joints:
      motor_front: 850
      motor_back_left: 852
      motor_back_right: 843
      lazy_susan: 569
    duration: 0.105
  - joints:
      motor_front: 846
      motor_back_left: 847
      motor_back_right: 836
      lazy_susan: 573
    duration: 0.104
  - joints:
      motor_front: 710
      motor_back_left: 710
      motor_back_right: 699
      lazy_susan: 576
    duration: 0.104
  - joints:
      motor_front: 720
      motor_back_left: 718
      motor_back_right: 715
      lazy_susan: 577
    duration: 0.105
  - joints:
      motor_front: 962
      motor_back_left: 966
      motor_back_right: 963
      lazy_susan: 580
    duration: 0.105
  - joints:
      motor_front: 1023
      motor_back_left: 1023
      motor_back_right: 1021
      lazy_susan: 581
    duration: 0.103
  - joints:
      motor_front: 919
      motor_back_left: 924
      motor_back_right: 917
      lazy_susan: 578
    duration: 0.1
  - joints:
      motor_front: 732
      motor_back_left: 738
      motor_back_right: 732
      lazy_susan: 578
    duration: 0.101
  - joints:
      motor_front: 763
      motor_back_left: 771
      motor_back_right: 766
      lazy_susan: 581
    duration: 0.103
  - joints:
      motor_front: 972
      motor_back_left: 979
      motor_back_right: 973
      lazy_susan: 580
    duration: 0.105
  - joints:
      motor_front: 868
      motor_back_left: 874
      motor_back_right: 870
      lazy_susan: 577
    duration: 0.103
  - joints:
      motor_front: 706
      motor_back_left: 710
      motor_back_right: 704
      lazy_susan: 580
    duration: 0.104
  - joints:
      motor_front: 918
      motor_back_left: 924
      motor_back_right: 918
      lazy_susan: 581
    duration: 0.103
  - joints:
      motor_front: 994
      motor_back_left: 1001
      motor_back_right: 994
      lazy_susan: 580
    duration: 0.1
  - joints:
      motor_front: 902
      motor_back_left: 906
      motor_back_right: 902
      lazy_susan: 578
    duration: 0.105
  - joints:
      motor_front: 728
      motor_back_left: 729
      motor_back_right: 728
      lazy_susan: 577
    duration: 0.1
  - joints:
      motor_front: 825
      motor_back_left: 828
      motor_back_right: 827
      lazy_susan: 580
    duration: 0.1
  - joints:
      motor_front: 971
      motor_back_left: 979
      motor_back_right: 974
      lazy_susan: 580
    duration: 0.102
  - joints:
      motor_front: 949
      motor_back_left: 956
      motor_back_right: 953
      lazy_susan: 579
    duration: 0.104
  - joints:
      motor_front: 738
      motor_back_left: 741
      motor_back_right: 739
      lazy_susan: 578
    duration: 0.104
  - joints:
      motor_front: 730
      motor_back_left: 738
      motor_back_right: 733
      lazy_susan: 581
    duration: 0.105
  - joints:
      motor_front: 938
      motor_back_left: 947
      motor_back_right: 940
      lazy_susan: 581
    duration: 0.105
  - joints:
      motor_front: 842
      motor_back_left: 847
      motor_back_right: 841
      lazy_susan: 579
    duration: 0.105
  - joints:
      motor_front: 797
      motor_back_left: 804
      motor_back_right: 797
      lazy_susan: 580
    duration: 0.103
  - joints:
      motor_front: 927
      motor_back_left: 937
      motor_back_right: 929
      lazy_susan: 583
    duration: 0.105
  - joints:
      motor_front: 945
      motor_back_left: 951
      motor_back_right: 946
      lazy_susan: 580
    duration: 0.105
  - joints:
      motor_front: 869
      motor_back_left: 875
      motor_back_right: 868
      lazy_susan: 580
    duration: 0.104
  - joints:
      motor_front: 831
      motor_back_left: 837
      motor_back_right: 829
      lazy_susan: 579
    duration: 0.104
  - joints:
      motor_front: 825
      motor_back_left: 831
      motor_back_right: 824
      lazy_susan: 579
    duration: 0.104
  - joints:
      motor_front: 831
      motor_back_left: 836
      motor_back_right: 830
      lazy_susan: 580
    duration: 0.103
  - joints:
      motor_front: 837
      motor_back_left: 840
      motor_back_right: 836
      lazy_susan: 580
    duration: 0.103
  - joints:
      motor_front: 849
      motor_back_left: 851
      motor_back_right: 846
      lazy_susan: 580
    duration: 0.103
  - joints:
      motor_front: 848
      motor_back_left: 852
      motor_back_right: 846
      lazy_susan: 580
    duration: 0.104
  - joints:
      motor_front: 855
      motor_back_left: 856
      motor_back_right: 851
      lazy_susan: 584
    duration: 0.106
  - joints:
      motor_front: 855
      motor_back_left: 856
      motor_back_right: 851
      lazy_susan: 584
    duration: 0.103
  - joints:
      motor_front: 856
      motor_back_left: 858
      motor_back_right: 849
      lazy_susan: 581
    duration: 0.104
  - joints:
      motor_front: 855
      motor_back_left: 858
      motor_back_right: 850
      lazy_susan: 577
    duration: 0.103
  - joints:
      motor_front: 856
      motor_back_left: 857
      motor_back_right: 849
      lazy_susan: 577
    duration: 0.104
