no_v2:
  keyframes:
  - joints:
      motor_front: 893
      motor_back_left: 844
      motor_back_right: 843
      lazy_susan: 582
    duration: 0.0
  - joints:
      motor_front: 891
      motor_back_left: 845
      motor_back_right: 843
      lazy_susan: 583
    duration: 0.103
  - joints:
      motor_front: 891
      motor_back_left: 846
      motor_back_right: 843
      lazy_susan: 583
    duration: 0.105
  - joints:
      motor_front: 891
      motor_back_left: 846
      motor_back_right: 842
      lazy_susan: 583
    duration: 0.105
  - joints:
      motor_front: 891
      motor_back_left: 846
      motor_back_right: 843
      lazy_susan: 584
    duration: 0.104
  - joints:
      motor_front: 890
      motor_back_left: 846
      motor_back_right: 843
      lazy_susan: 585
    duration: 0.103
  - joints:
      motor_front: 890
      motor_back_left: 845
      motor_back_right: 844
      lazy_susan: 584
    duration: 0.1
  - joints:
      motor_front: 885
      motor_back_left: 850
      motor_back_right: 844
      lazy_susan: 569
    duration: 0.105
  - joints:
      motor_front: 881
      motor_back_left: 862
      motor_back_right: 835
      lazy_susan: 524
    duration: 0.103
  - joints:
      motor_front: 887
      motor_back_left: 860
      motor_back_right: 831
      lazy_susan: 473
    duration: 0.101
  - joints:
      motor_front: 888
      motor_back_left: 858
      motor_back_right: 833
      lazy_susan: 452
    duration: 0.1
  - joints:
      motor_front: 884
      motor_back_left: 862
      motor_back_right: 833
      lazy_susan: 464
    duration: 0.102
  - joints:
      motor_front: 883
      motor_back_left: 863
      motor_back_right: 833
      lazy_susan: 533
    duration: 0.104
  - joints:
      motor_front: 874
      motor_back_left: 864
      motor_back_right: 841
      lazy_susan: 673
    duration: 0.102
  - joints:
      motor_front: 867
      motor_back_left: 863
      motor_back_right: 849
      lazy_susan: 684
    duration: 0.102
  - joints:
      motor_front: 862
      motor_back_left: 870
      motor_back_right: 847
      lazy_susan: 633
    duration: 0.106
  - joints:
      motor_front: 862
      motor_back_left: 877
      motor_back_right: 841
      lazy_susan: 568
    duration: 0.103
  - joints:
      motor_front: 864
      motor_back_left: 871
      motor_back_right: 844
      lazy_susan: 510
    duration: 0.103
  - joints:
      motor_front: 862
      motor_back_left: 873
      motor_back_right: 844
      lazy_susan: 472
    duration: 0.1
  - joints:
      motor_front: 864
      motor_back_left: 879
      motor_back_right: 837
      lazy_susan: 457
    duration: 0.101
  - joints:
      motor_front: 867
      motor_back_left: 877
      motor_back_right: 835
      lazy_susan: 481
    duration: 0.104
  - joints:
      motor_front: 872
      motor_back_left: 874
      motor_back_right: 833
      lazy_susan: 544
    duration: 0.103
  - joints:
      motor_front: 867
      motor_back_left: 876
      motor_back_right: 836
      lazy_susan: 607
    duration: 0.103
  - joints:
      motor_front: 861
      motor_back_left: 882
      motor_back_right: 836
      lazy_susan: 647
    duration: 0.1
  - joints:
      motor_front: 859
      motor_back_left: 876
      motor_back_right: 844
      lazy_susan: 658
    duration: 0.1
  - joints:
      motor_front: 860
      motor_back_left: 875
      motor_back_right: 844
      lazy_susan: 602
    duration: 0.102
  - joints:
      motor_front: 864
      motor_back_left: 872
      motor_back_right: 842
      lazy_susan: 582
    duration: 0.1
  - joints:
      motor_front: 866
      motor_back_left: 870
      motor_back_right: 842
      lazy_susan: 581
    duration: 0.102
  - joints:
      motor_front: 867
      motor_back_left: 870
      motor_back_right: 842
      lazy_susan: 581
    duration: 0.101
  - joints:
      motor_front: 864
      motor_back_left: 870
      motor_back_right: 844
      lazy_susan: 580
    duration: 0.104
  - joints:
      motor_front: 866
      motor_back_left: 868
      motor_back_right: 845
      lazy_susan: 581
    duration: 0.106
  - joints:
      motor_front: 868
      motor_back_left: 866
      motor_back_right: 845
      lazy_susan: 581
    duration: 0.103
  - joints:
      motor_front: 871
      motor_back_left: 860
      motor_back_right: 848
      lazy_susan: 585
    duration: 0.105
  - joints:
      motor_front: 870
      motor_back_left: 861
      motor_back_right: 847
      lazy_susan: 585
    duration: 0.104
