sad:
  keyframes:
  - joints:
      motor_front: 885
      motor_back_left: 835
      motor_back_right: 860
      lazy_susan: 588
    duration: 0.0
  - joints:
      motor_front: 885
      motor_back_left: 835
      motor_back_right: 860
      lazy_susan: 588
    duration: 0.103
  - joints:
      motor_front: 881
      motor_back_left: 837
      motor_back_right: 861
      lazy_susan: 589
    duration: 0.1
  - joints:
      motor_front: 881
      motor_back_left: 838
      motor_back_right: 860
      lazy_susan: 589
    duration: 0.102
  - joints:
      motor_front: 880
      motor_back_left: 839
      motor_back_right: 860
      lazy_susan: 589
    duration: 0.103
  - joints:
      motor_front: 881
      motor_back_left: 839
      motor_back_right: 859
      lazy_susan: 589
    duration: 0.101
  - joints:
      motor_front: 884
      motor_back_left: 838
      motor_back_right: 858
      lazy_susan: 589
    duration: 0.101
  - joints:
      motor_front: 888
      motor_back_left: 835
      motor_back_right: 855
      lazy_susan: 588
    duration: 0.1
  - joints:
      motor_front: 893
      motor_back_left: 833
      motor_back_right: 853
      lazy_susan: 588
    duration: 0.102
  - joints:
      motor_front: 899
      motor_back_left: 830
      motor_back_right: 850
      lazy_susan: 589
    duration: 0.105
  - joints:
      motor_front: 909
      motor_back_left: 825
      motor_back_right: 845
      lazy_susan: 589
    duration: 0.101
  - joints:
      motor_front: 926
      motor_back_left: 816
      motor_back_right: 837
      lazy_susan: 590
    duration: 0.105
  - joints:
      motor_front: 981
      motor_back_left: 783
      motor_back_right: 815
      lazy_susan: 592
    duration: 0.103
  - joints:
      motor_front: 1003
      motor_back_left: 771
      motor_back_right: 805
      lazy_susan: 592
    duration: 0.101
  - joints:
      motor_front: 1020
      motor_back_left: 764
      motor_back_right: 794
      lazy_susan: 594
    duration: 0.101
  - joints:
      motor_front: 1023
      motor_back_left: 760
      motor_back_right: 786
      lazy_susan: 594
    duration: 0.101
  - joints:
      motor_front: 1023
      motor_back_left: 761
      motor_back_right: 783
      lazy_susan: 595
    duration: 0.104
  - joints:
      motor_front: 1023
      motor_back_left: 762
      motor_back_right: 783
      lazy_susan: 595
    duration: 0.1
  - joints:
      motor_front: 1023
      motor_back_left: 764
      motor_back_right: 784
      lazy_susan: 595
    duration: 0.106
  - joints:
      motor_front: 1017
      motor_back_left: 771
      motor_back_right: 791
      lazy_susan: 596
    duration: 0.103
  - joints:
      motor_front: 987
      motor_back_left: 784
      motor_back_right: 808
      lazy_susan: 597
    duration: 0.1
  - joints:
      motor_front: 951
      motor_back_left: 802
      motor_back_right: 826
      lazy_susan: 599
    duration: 0.105
  - joints:
      motor_front: 917
      motor_back_left: 820
      motor_back_right: 843
      lazy_susan: 601
    duration: 0.105
  - joints:
      motor_front: 814
      motor_back_left: 876
      motor_back_right: 890
      lazy_susan: 607
    duration: 0.101
  - joints:
      motor_front: 731
      motor_back_left: 928
      motor_back_right: 920
      lazy_susan: 610
    duration: 0.104
  - joints:
      motor_front: 652
      motor_back_left: 980
      motor_back_right: 947
      lazy_susan: 613
    duration: 0.104
  - joints:
      motor_front: 596
      motor_back_left: 1022
      motor_back_right: 962
      lazy_susan: 613
    duration: 0.104
  - joints:
      motor_front: 573
      motor_back_left: 1023
      motor_back_right: 972
      lazy_susan: 617
    duration: 0.101
  - joints:
      motor_front: 574
      motor_back_left: 1023
      motor_back_right: 981
      lazy_susan: 632
    duration: 0.105
  - joints:
      motor_front: 577
      motor_back_left: 1020
      motor_back_right: 983
      lazy_susan: 637
    duration: 0.103
  - joints:
      motor_front: 583
      motor_back_left: 1014
      motor_back_right: 983
      lazy_susan: 643
    duration: 0.103
  - joints:
      motor_front: 590
      motor_back_left: 1007
      motor_back_right: 982
      lazy_susan: 652
    duration: 0.102
  - joints:
      motor_front: 595
      motor_back_left: 995
      motor_back_right: 989
      lazy_susan: 664
    duration: 0.105
  - joints:
      motor_front: 596
      motor_back_left: 984
      motor_back_right: 999
      lazy_susan: 675
    duration: 0.103
  - joints:
      motor_front: 591
      motor_back_left: 986
      motor_back_right: 1002
      lazy_susan: 669
    duration: 0.103
  - joints:
      motor_front: 587
      motor_back_left: 1022
      motor_back_right: 970
      lazy_susan: 593
    duration: 0.102
  - joints:
      motor_front: 589
      motor_back_left: 1023
      motor_back_right: 956
      lazy_susan: 561
    duration: 0.105
  - joints:
      motor_front: 592
      motor_back_left: 1023
      motor_back_right: 960
      lazy_susan: 567
    duration: 0.104
  - joints:
      motor_front: 596
      motor_back_left: 1004
      motor_back_right: 979
      lazy_susan: 608
    duration: 0.102
  - joints:
      motor_front: 607
      motor_back_left: 981
      motor_back_right: 991
      lazy_susan: 646
    duration: 0.104
  - joints:
      motor_front: 612
      motor_back_left: 979
      motor_back_right: 988
      lazy_susan: 654
    duration: 0.105
  - joints:
      motor_front: 613
      motor_back_left: 1003
      motor_back_right: 964
      lazy_susan: 605
    duration: 0.103
  - joints:
      motor_front: 617
      motor_back_left: 1014
      motor_back_right: 948
      lazy_susan: 569
    duration: 0.104
  - joints:
      motor_front: 614
      motor_back_left: 1012
      motor_back_right: 954
      lazy_susan: 584
    duration: 0.1
  - joints:
      motor_front: 609
      motor_back_left: 987
      motor_back_right: 983
      lazy_susan: 648
    duration: 0.101
  - joints:
      motor_front: 615
      motor_back_left: 970
      motor_back_right: 994
      lazy_susan: 663
    duration: 0.102
  - joints:
      motor_front: 615
      motor_back_left: 1023
      motor_back_right: 942
      lazy_susan: 569
    duration: 0.105
  - joints:
      motor_front: 619
      motor_back_left: 1020
      motor_back_right: 941
      lazy_susan: 569
    duration: 0.103
  - joints:
      motor_front: 618
      motor_back_left: 990
      motor_back_right: 971
      lazy_susan: 626
    duration: 0.1
  - joints:
      motor_front: 621
      motor_back_left: 964
      motor_back_right: 994
      lazy_susan: 668
    duration: 0.104
  - joints:
      motor_front: 612
      motor_back_left: 987
      motor_back_right: 980
      lazy_susan: 627
    duration: 0.101
  - joints:
      motor_front: 620
      motor_back_left: 1010
      motor_back_right: 949
      lazy_susan: 579
    duration: 0.104
  - joints:
      motor_front: 616
      motor_back_left: 1016
      motor_back_right: 948
      lazy_susan: 571
    duration: 0.101
  - joints:
      motor_front: 608
      motor_back_left: 996
      motor_back_right: 976
      lazy_susan: 614
    duration: 0.102
  - joints:
      motor_front: 613
      motor_back_left: 966
      motor_back_right: 1000
      lazy_susan: 660
    duration: 0.1
  - joints:
      motor_front: 618
      motor_back_left: 958
      motor_back_right: 1004
      lazy_susan: 667
    duration: 0.104
  - joints:
      motor_front: 610
      motor_back_left: 979
      motor_back_right: 990
      lazy_susan: 643
    duration: 0.101
  - joints:
      motor_front: 609
      motor_back_left: 993
      motor_back_right: 977
      lazy_susan: 626
    duration: 0.101
  - joints:
      motor_front: 606
      motor_back_left: 996
      motor_back_right: 977
      lazy_susan: 620
    duration: 0.102
  - joints:
      motor_front: 586
      motor_back_left: 1010
      motor_back_right: 983
      lazy_susan: 624
    duration: 0.104
  - joints:
      motor_front: 570
      motor_back_left: 1023
      motor_back_right: 986
      lazy_susan: 626
    duration: 0.102
  - joints:
      motor_front: 565
      motor_back_left: 1023
      motor_back_right: 991
      lazy_susan: 631
    duration: 0.1
  - joints:
      motor_front: 574
      motor_back_left: 1016
      motor_back_right: 989
      lazy_susan: 634
    duration: 0.101
  - joints:
      motor_front: 594
      motor_back_left: 1000
      motor_back_right: 986
      lazy_susan: 636
    duration: 0.1
  - joints:
      motor_front: 594
      motor_back_left: 1000
      motor_back_right: 986
      lazy_susan: 636
    duration: 0.103
  - joints:
      motor_front: 647
      motor_back_left: 965
      motor_back_right: 967
      lazy_susan: 637
    duration: 0.1
  - joints:
      motor_front: 672
      motor_back_left: 951
      motor_back_right: 957
      lazy_susan: 637
    duration: 0.106
  - joints:
      motor_front: 703
      motor_back_left: 930
      motor_back_right: 946
      lazy_susan: 638
    duration: 0.103
  - joints:
      motor_front: 740
      motor_back_left: 908
      motor_back_right: 930
      lazy_susan: 636
    duration: 0.103
  - joints:
      motor_front: 771
      motor_back_left: 888
      motor_back_right: 921
      lazy_susan: 635
    duration: 0.102
  - joints:
      motor_front: 801
      motor_back_left: 869
      motor_back_right: 909
      lazy_susan: 636
    duration: 0.101
  - joints:
      motor_front: 817
      motor_back_left: 861
      motor_back_right: 902
      lazy_susan: 635
    duration: 0.105
  - joints:
      motor_front: 836
      motor_back_left: 850
      motor_back_right: 892
      lazy_susan: 633
    duration: 0.104
  - joints:
      motor_front: 833
      motor_back_left: 851
      motor_back_right: 895
      lazy_susan: 632
    duration: 0.1
  - joints:
      motor_front: 834
      motor_back_left: 849
      motor_back_right: 897
      lazy_susan: 630
    duration: 0.105
  - joints:
      motor_front: 842
      motor_back_left: 843
      motor_back_right: 894
      lazy_susan: 627
    duration: 0.103
  - joints:
      motor_front: 842
      motor_back_left: 842
      motor_back_right: 895
      lazy_susan: 625
    duration: 0.101
  - joints:
      motor_front: 847
      motor_back_left: 838
      motor_back_right: 894
      lazy_susan: 623
    duration: 0.105
  - joints:
      motor_front: 851
      motor_back_left: 833
      motor_back_right: 895
      lazy_susan: 622
    duration: 0.1
  - joints:
      motor_front: 855
      motor_back_left: 830
      motor_back_right: 894
      lazy_susan: 621
    duration: 0.105
