controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    blossom_position_controller:
      type: position_controllers/JointGroupPositionController

blossom_position_controller:
  ros__parameters:
    joints:
      - base_pan
      - string_front
      - string_back_right
      - string_back_left
